apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.service_name}}
  description: {{cookiecutter.description}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner_team}}
